-- MySQL Script generated by MySQL Workbench
-- qua 18 nov 2020 13:48:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPindura2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbPindura2` ;

-- -----------------------------------------------------
-- Schema dbPindura2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPindura2` ;
USE `dbPindura2` ;

-- -----------------------------------------------------
-- Table `dbPindura2`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPindura2`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nmPessoa` VARCHAR(127) NOT NULL,
  `dsPessoa` VARCHAR(255) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 10002;


-- -----------------------------------------------------
-- Table `dbPindura2`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPindura2`.`Consumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descritivo` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `pago` CHAR(1) NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Consumo_Pessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `dbPindura2`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Consumo_Pessoa_idx` ON `dbPindura2`.`Consumo` (`idPessoa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbPindura2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPindura2`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nmUsuario` VARCHAR(45) NOT NULL,
  `pwUsuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nmUsuario_UNIQUE` ON `dbPindura2`.`Usuario` (`nmUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbPindura2`.`logPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPindura2`.`logPessoa` (
  `idLog` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NULL,
  `nmPessoa` VARCHAR(127) NULL,
  `dsPessoa` VARCHAR(255) NULL,
  `acao` VARCHAR(45) NULL,
  PRIMARY KEY (`idLog`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dbPindura2`.`Pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPindura2`;
INSERT INTO `dbPindura2`.`Pessoa` (`idPessoa`, `nmPessoa`, `dsPessoa`) VALUES (100, 'Marcos A. Lucas', 'Professor da URI Erechim');
INSERT INTO `dbPindura2`.`Pessoa` (`idPessoa`, `nmPessoa`, `dsPessoa`) VALUES (200, 'Evangisvaldo da Silva', 'Voluntário local');
INSERT INTO `dbPindura2`.`Pessoa` (`idPessoa`, `nmPessoa`, `dsPessoa`) VALUES (300, 'Scatamáfia da Silva', 'Desenvolvedora chefe da empresa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbPindura2`.`Consumo`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPindura2`;
INSERT INTO `dbPindura2`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (101, 'halls', 1.99, 'S', 100);
INSERT INTO `dbPindura2`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (102, 'refri', 3, 'N', 100);
INSERT INTO `dbPindura2`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (201, 'refrigerante', 6, 'N', 200);
INSERT INTO `dbPindura2`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (202, 'diversos', 14, 'N', 200);
INSERT INTO `dbPindura2`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (301, 'agua com gas', 4, 'S', 300);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbPindura2`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPindura2`;
INSERT INTO `dbPindura2`.`Usuario` (`idUsuario`, `nmUsuario`, `pwUsuario`) VALUES (0, 'admin', '21232f297a57a5a743894a0e4a801fc3');

COMMIT;

USE `dbPindura2`;

DELIMITER $$
USE `dbPindura2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `dbPindura2`.`Pessoa_AFTER_INSERT` AFTER INSERT ON `Pessoa` FOR EACH ROW
BEGIN
  INSERT INTO logPessoa (idLog, idPessoa, nmPessoa, dsPessoa, acao) VALUES
  (0, new.idPessoa, new.nmPessoa, new.dsPessoa, 'INSERIR');
END$$

USE `dbPindura2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `dbPindura2`.`Pessoa_BEFORE_UPDATE` BEFORE UPDATE ON `Pessoa` FOR EACH ROW
BEGIN
  INSERT INTO logPessoa (idLog, idPessoa, nmPessoa, dsPessoa, acao) VALUES
  (0, old.idPessoa, old.nmPessoa, old.dsPessoa, 'TENTOU ALTERAR');
END$$

USE `dbPindura2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `dbPindura2`.`Pessoa_AFTER_UPDATE` AFTER UPDATE ON `Pessoa` FOR EACH ROW
BEGIN
  INSERT INTO logPessoa (idLog, idPessoa, nmPessoa, dsPessoa, acao) VALUES
  (0, new.idPessoa, new.nmPessoa, new.dsPessoa, 'ALTEROU PARA');
END$$

USE `dbPindura2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `dbPindura2`.`Pessoa_BEFORE_DELETE` BEFORE DELETE ON `Pessoa` FOR EACH ROW
BEGIN
  INSERT INTO logPessoa (idLog, idPessoa, nmPessoa, dsPessoa, acao) VALUES
  (0, old.idPessoa, old.nmPessoa, old.dsPessoa, 'EXCLUIU');
END$$


DELIMITER ;
