-- MySQL Script generated by MySQL Workbench
-- qua 18 nov 2020 13:48:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPindura1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbPindura1` ;

-- -----------------------------------------------------
-- Schema dbPindura1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPindura1` ;
SHOW WARNINGS;
USE `dbPindura1` ;

-- -----------------------------------------------------
-- Table `dbPindura1`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPindura1`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nmPessoa` VARCHAR(127) NOT NULL,
  `dsPessoa` VARCHAR(255) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 10002;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dbPindura1`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPindura1`.`Consumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descritivo` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `pago` CHAR(1) NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dbPindura1`.`Pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPindura1`;
INSERT INTO `dbPindura1`.`Pessoa` (`idPessoa`, `nmPessoa`, `dsPessoa`) VALUES (100, 'Marcos A. Lucas', 'Professor da URI Erechim');
INSERT INTO `dbPindura1`.`Pessoa` (`idPessoa`, `nmPessoa`, `dsPessoa`) VALUES (200, 'Evangisvaldo da Silva', 'Voluntário local');
INSERT INTO `dbPindura1`.`Pessoa` (`idPessoa`, `nmPessoa`, `dsPessoa`) VALUES (300, 'Scatamáfia da Silva', 'Desenvolvedora chefe da empresa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbPindura1`.`Consumo`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbPindura1`;
INSERT INTO `dbPindura1`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (101, 'halls', 1.99, 'S', 100);
INSERT INTO `dbPindura1`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (102, 'refri', 3, 'N', 100);
INSERT INTO `dbPindura1`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (201, 'refrigerante', 6, 'N', 200);
INSERT INTO `dbPindura1`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (202, 'diversos', 14, 'N', 200);
INSERT INTO `dbPindura1`.`Consumo` (`id`, `descritivo`, `valor`, `pago`, `idPessoa`) VALUES (301, 'agua com gas', 4, 'S', 300);

COMMIT;

